_wandb:
    value:
        cli_version: 0.18.6
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 55
            "2":
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.10.12
            "5": 0.18.6
            "8":
                - 3
                - 5
            "12": 0.18.6
            "13": windows-amd64
architecture:
    value: CNN
dataset:
    value: CIFAR-100
epochs:
    value: 10
learning_rate:
    value: 0.02
